---
version: '2'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/schema.sql
    volumes:
      - ./artifacts/schema.sql:/data/application/schema.sql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"